name: Build site
# Only build and deploy when pushed onto `master`
on:
  push:
    branches:
      - master

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      # Fetch the code
      - name: Checkout
        uses: actions/checkout@v2
      
      # Install Zola from the github releases page
      - name: Install Zola
        run: |
          curl -L "https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz" | sudo tar xzf - -C /usr/local/bin

      # Build the site and initialize it as a git repo
      - name: Build site
        run: zola build --base-url https://team1157.github.io/team1157.org
      
      # Commit and push the built site
      - name: Push site
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build and deploy site"
          
          
